export const ANSWER_FETCH_COMPLETED = 'ANSWER_FETCH_COMPLETED';

export const ANSWER_ADD_COMPLETED = 'ANSWER_ADD_COMPLETED';
export const ANSWER_ADD_STARTED = 'ANSWER_ADD_STARTED';
export const ANSWER_ADD_FAILED = 'ANSWER_ADD_FAILED';