export const QUESTIONNAIRE_FETCH_STARTED = 'QUESTIONNAIRE_FETCH_STARTED'
export const QUESTIONNAIRE_FETCH_COMPLETED = 'QUESTIONNAIRE_FETCH_COMPLETED'
export const QUESTIONNAIRE_FETCH_FAILED = 'QUESTIONNAIRE_FETCH_FAILED '