export const REPORT_FETCH_STARTED = 'REPORT_FETCH_STARTED';
export const REPORT_FETCH_COMPLETED = 'REPORT_FETCH_COMPLETED';
export const REPORT_FETCH_FAILED = 'REPORT_FETCH_FAILED';

export const REPORT_ADD_STARTED = 'REPORT_ADD_STARTED';
export const REPORT_ADD_COMPLETED = 'REPORT_ADD_COMPLETED';
export const REPORT_ADD_FAILED = 'REPORT_ADD_FAILED';

export const REPORT_REMOVE_STARTED = 'REPORT_REMOVE_STARTED';
export const REPORT_REMOVE_COMPLETED = 'REPORT_REMOVE_COMPLETED';
export const REPORT_REMOVE_FAILED = 'REPORT_REMOVE_FAILED';
